CREATE TABLE `log` (
	`id` INT(11) UNSIGNED AUTO_INCREMENT,
	`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`uuid` VARCHAR(40) NOT NULL,
	`log` VARCHAR(25) NOT NULL,
	`message` TEXT NOT NULL,
	PRIMARY KEY (`id` )
) ENGINE=Archive DEFAULT CHARSET=utf8;
